version: '3.1'

services:
  web:
    image: book-rpg-site
    container_name: book-rpg-site
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:80
    restart: always